server:
  port: 8082

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:woowacourse'
    username: hkjin
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console # localhost:8081/h2-console
